# URL
title: SIMPLE                        # 站点名
description: A Jekyll Theme          # 站点描述
url: https://professordeng.com       # 域名
baseurl: /simple                     # 根目录

# 社交帐号
## 会在页面底部显示
github: professordeng
mail: professordeng@qq.com
weibo: codeng
linkedin: professordeng

# 站点资源
img: /simple/assets/img          # 图片库
css: /simple/assets/css          # CSS 样式库
js:  /simple/assets/js           # js 库
cdn: https://cdn.jsdelivr.net/gh/professordeng/simple@gh-pages/assets/img # CDN 加速

# 背景图片
## true 为全站启用 Bing 每日美图，若为 false 则不启用
## 你可以在文章（即 _post 目录下的 md 文件）的 front matter 部分通过 wallpaper: ImageURL 来单独设定文章的背景图
bg: true    # 是否使用 Bing 每日美图

# Jekyll 插件
## Docs: https://pages.github.com/versions/
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
  - jekyll-avatar
  - jekyll-mentions

# 评论系统（本主题使用 gitalk）
## Docs: https://github.com/gitalk/gitalk/blob/master/readme-cn.md
gitalk:
  enable: true 
  clientID: 6e42adfac0bf61e180f6
  clientSecret: d1ed44fc8888bbb2bcafb6bbc819ac9dddca5b71
  repo: simple
  owner: professordeng
  admin: professordeng
  id: simple      # 默认是 location.pathname
  title: simple   # issue 标题
  body: simple
  

# Google Analytics
## Docs: https://analytics.google.com/analytics/web/
google-analytics: UA-165708741-1

# 默认 _post 文件夹用 post 布局，不用改
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"