url: https://professordeng.com   # 地址
baseurl: /simple                 # 根目录

github: professordeng
mail: professordeng@qq.com
weibo: codeng
zhihu: professordeng
linkedin: professordeng

img: /simple/assets/img          # 图片库
css: /simple/assets/css          # CSS 样式库
js:  /simple/assets/js           # js 库
cdn: https://cdn.jsdelivr.net/gh/professordeng/simple@gh-pages/assets/img