# 导航栏
navigation:
- name: Home
  link: /
- name: About
  link: /about.html
  
# 社交
social:
- icon: github
  link: https://www.github.com/professordeng
- icon: envelope
  link: mailto:professordeng@qq.com
- icon: rss
  link: /feed.xml