# Customize site navigation
nav:
- name: Home
  url: /
- name: Archives
  url: /archives.html
- name: About
  url: /about.html

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- icon: github
  link: https://github.com/professordeng/simple
- icon: false    # weibo
  link: https://weibo.com/codeng
- icon: telegram
  link: https://t.me/jekyll_simple
- icon: zhihu
  link: https://zhihu.com/people/professordeng
- icon: false    # linkedin
  link: https://linkedin.com/in/professordeng
  
# Customize site text
prev: Newer
next: Older

prev_page: Newer
next_page: Older

search_tip: Press enter to search
searching: Searching

new: New

read_more: Read More

edit: 编辑
